services:
  django:
    container_name: django
    hostname: django
    image: django_custom_image
    build:
      context: ./five_let_app
      dockerfile: Dockerfile
    volumes:
      - static_volume:/static

    expose:
      - 8000
    ports:
      - "8001:8000"

#    command: ["ls","/app","/app/old_app.sh"]
#    entrypoint: ["/bin/bash", "-c", "/app/app.sh"]
#    command: ["/app/old_app.sh"]
#    command: ["cd app","poetry run manage.py runserver"]
#    command: []
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx_custom_image
    build:
      context: ./nginx
    volumes:
      - static_volume:/static
    depends_on:
      - django
#    links:
#      - django
    ports:
      - "1337:80"
volumes:
  static_volume: